import {useEffect,useMemo,useState} from "react";
import {api} from "./api";
const impactLabel:any={BLOCKING:"Bloquant",MAJOR:"Majeur",MINOR:"Mineur"};
export function AccessibilityAdmin(){
 const[audits,setAudits]=useState<any[]>([]),[selected,setSelected]=useState<any>(null),[detail,setDetail]=useState<any>(null),[filter,setFilter]=useState("ALL"),[reports,setReports]=useState<any[]>([]),[msg,setMsg]=useState("");
 async function load(){setAudits(await api.accessibilityAudits());setReports(await api.accessibilityReports())} useEffect(()=>{load()},[]);
 async function open(a:any,focusPending=false){setSelected(a);const d=await api.accessibilityAudit(a.id);setDetail(d);setFilter("ALL");if(focusPending&&d.audit.status==="DRAFT")setTimeout(()=>document.querySelector(".rgaa-criterion.pending")?.scrollIntoView({behavior:"smooth",block:"center"}),80)}
 async function create(){const title=prompt("Titre de l’audit","Audit RGAA 4.1.2 — PCIF Académie");if(!title)return;const a=await api.createAccessibilityAudit({title,applicationVersion:"0.32.3"});await load();await open(a,true)}
 const rows=useMemo(()=>{if(!detail)return[];const by=new Map(detail.results.map((x:any)=>[x.criterion_code,x]));return detail.criteria.map((c:any)=>({...c,auditId:detail.audit.id,result:by.get(c.code)})).filter((x:any)=>filter==="ALL"||x.result?.status===filter)},[detail,filter]);
 if(!selected)return <><div className="hero"><div><small>Conformité & confiance</small><h1>Audits RGAA 4.1.2</h1><p>Auditer les 106 critères, qualifier les non-conformités, valider l’audit puis publier un rapport public.</p></div><button className="primary" onClick={create}>+ Nouvel audit</button></div><section className="panel"><h2>Audits</h2>{!audits.length?<p>Aucun audit.</p>:audits.map(a=>{const done=Number(a.completed||0),draft=a.status==="DRAFT";const label=draft?(done===0?"Commencer l’audit":done<106?"Continuer l’audit":"Vérifier et clôturer"):(a.published_report_slug?"Voir le rapport publié":"Voir le rapport");return <article className="rgaa-audit-card" key={a.id}><div><b>{a.title}</b><small>Version {a.application_version} · {done}/106 critères · {draft?"Brouillon":"Clôturé"}</small></div><div className="hero-actions"><button className={draft?"primary":""} onClick={()=>draft?open(a,true):open(a)}>{label}</button>{!draft&&a.published_report_slug&&<a className="primary-link" href={`/accessibilite/rapports/${encodeURIComponent(a.published_report_slug)}`} target="_blank" rel="noreferrer">Rapport public</a>}</div></article>})}</section><section className="panel"><h2>Rapports publiés</h2>{reports.map(r=><article className="rgaa-audit-card" key={r.id}><div><b>{r.title}</b><small>{r.slug} · {r.is_current?"Rapport courant":"Archivé"}</small></div><div className="hero-actions"><a className="primary-link" href={`/accessibilite/rapports/${encodeURIComponent(r.slug)}`} target="_blank" rel="noreferrer">Ouvrir le rapport</a>{r.is_current&&<button onClick={async()=>{await api.unpublishAccessibilityReport(r.id);await load()}}>Dépublier</button>}</div></article>)}</section></>;
 const s=detail.stats;
 return <><button onClick={()=>{setSelected(null);setDetail(null)}}>← Audits</button><div className="hero"><div><small>Audit RGAA 4.1.2</small><h1>{detail.audit.title}</h1><p>Version auditée : {detail.audit.application_version} · {s.done}/106 critères renseignés.</p></div><div className="hero-actions">{detail.audit.status==="DRAFT"&&s.done===106&&<button className="primary" onClick={async()=>{try{await api.closeAccessibilityAudit(detail.audit.id);await open(detail.audit);setMsg("Audit validé et clôturé. Vous pouvez maintenant publier le rapport.")}catch{setMsg("Les 106 critères doivent être renseignés.")}}}>Valider et clôturer l’audit</button>}{detail.audit.status==="CLOSED"&&!detail.report&&<button className="primary" onClick={async()=>{const r=await api.publishAccessibilityAudit(detail.audit.id);setMsg(`Rapport publié : ${r.slug}`);await load();await open(detail.audit);window.open(`/accessibilite/rapports/${encodeURIComponent(r.slug)}`,"_blank","noopener,noreferrer")}}>Publier le rapport</button>}{detail.audit.status==="CLOSED"&&detail.report&&<a className="primary-link" href={`/accessibilite/rapports/${encodeURIComponent(detail.report.slug)}`} target="_blank" rel="noreferrer">Voir le rapport publié</a>}</div></div>{msg&&<div className="notice" role="status">{msg}</div>}{detail.audit.status==="DRAFT"&&<div className="notice" role="status">{s.done===0?"Commencez l’audit en répondant C, NC ou NA à chaque critère.":s.done<106?`Audit en cours : ${106-s.done} critère(s) restent à renseigner.`:"Les 106 critères sont renseignés. Vérifiez les réponses puis validez et clôturez l’audit."}</div>}<section className="rgaa-summary"><div><strong>{s.rate==null?"—":`${s.rate} %`}</strong><span>Taux global</span></div><div className="bad"><strong>{s.nc}</strong><span>Non conformes · {s.blocking} bloquant(s)</span></div><div className="good"><strong>{s.c}</strong><span>Conformes</span></div><div><strong>{s.na}</strong><span>Non applicables</span></div></section><div className="admin-tabs"><button className={filter==="ALL"?"active":""} onClick={()=>setFilter("ALL")}>106 critères</button><button className={filter==="NC"?"active":""} onClick={()=>setFilter("NC")}>Non-conformités ({s.nc})</button><button className={filter==="C"?"active":""} onClick={()=>setFilter("C")}>Conformes</button><button className={filter==="NA"?"active":""} onClick={()=>setFilter("NA")}>Non applicables</button></div><section className="rgaa-list">{rows.map((x:any)=><Criterion key={x.code} item={x} locked={detail.audit.status!=="DRAFT"} saved={async()=>open(detail.audit)}/>)}</section></>
}
function Criterion({item,locked,saved}:{item:any;locked:boolean;saved:()=>void}){const r=item.result||{};const[status,setStatus]=useState(r.status||"");const[title,setTitle]=useState(r.error_title||"");const[desc,setDesc]=useState(r.error_description||"");const[rec,setRec]=useState(r.recommendation||"");const[impact,setImpact]=useState(r.impact||"MAJOR");const[easy,setEasy]=useState(!!r.easy_fix);const[na,setNa]=useState(r.na_justification||"");const[evidence,setEvidence]=useState(r.evidence||"");const[err,setErr]=useState("");async function save(){try{await api.saveAccessibilityResult(item.auditId||item.result?.audit_id||"",item.code,{status,errorTitle:title,errorDescription:desc,recommendation:rec,impact:status==="NC"?impact:null,easyFix:easy,naJustification:na,evidence});await saved()}catch(e:any){setErr(e.message)}}
 // audit id is injected by parent result when existing; for new results infer from DOM dataset is not safe, so parent wrapper patches below
 return <article className={`rgaa-criterion ${status||"pending"}`}><header><div><b>{item.code} · {item.theme}</b><span>{item.label}</span></div><a href={item.officialUrl} target="_blank" rel="noreferrer">Référence officielle ↗</a></header><div className="rgaa-status">{["C","NC","NA"].map(v=><label key={v}><input type="radio" disabled={locked} checked={status===v} onChange={()=>setStatus(v)}/>{v}</label>)}</div>{status==="NC"&&<div className="rgaa-finding"><label>Titre de l’erreur<input disabled={locked} value={title} onChange={e=>setTitle(e.target.value)}/></label><label>Description de l’erreur<textarea disabled={locked} value={desc} onChange={e=>setDesc(e.target.value)}/></label><label>Proposition de correction<textarea disabled={locked} value={rec} onChange={e=>setRec(e.target.value)}/></label><fieldset><legend>Impact sur l’usager</legend>{Object.keys(impactLabel).map(v=><label key={v}><input type="radio" disabled={locked} checked={impact===v} onChange={()=>setImpact(v)}/>{impactLabel[v]}</label>)}</fieldset><label className="check"><input type="checkbox" disabled={locked} checked={easy} onChange={e=>setEasy(e.target.checked)}/> Facile à corriger</label></div>}{status==="NA"&&<label>Justification de non-applicabilité<textarea disabled={locked} value={na} onChange={e=>setNa(e.target.value)}/></label>} {status&&<label>Preuve / observation<textarea disabled={locked} value={evidence} onChange={e=>setEvidence(e.target.value)}/></label>}{err&&<div className="error">{err}</div>}{!locked&&status&&<button className="primary" onClick={save}>Enregistrer</button>}</article>}
