import React,{useMemo,useState} from "react";
import type {Me} from "./api";

export type HelpContext="home"|"pilotage"|"workshops"|"onf"|"processes"|"audit"|"auditManagement"|"admin";
type Topic={id:string;title:string;summary:string;category:string;keywords:string[];contexts?:HelpContext[];auditor?:boolean;body:React.ReactNode};
type CapabilityStatus="AVAILABLE"|"IN_DEVELOPMENT"|"PLANNED";
type Capability={id:string;title:string;description:string;status:CapabilityStatus};
const S=({children}:{children:React.ReactNode})=><section className="help-topic-section">{children}</section>;
const topics:Topic[]=[
{id:"discover",title:"Découvrir PCIF Académie",summary:"La démarche, les espaces de travail et le fil conducteur d'une campagne.",category:"Découvrir",keywords:["débuter","démarche","campagne"],body:<><S><h3>À quoi ça sert ?</h3><p>PCIF Académie aide une équipe à décrire son organisation, ses pratiques et ses risques, puis à décider des actions utiles. Le contrôle interne est traité comme une démarche d'amélioration continue, pas comme un questionnaire isolé.</p></S><S><h3>Le fil conducteur</h3><p><b>Qui fait quoi ?</b> → <b>Comment travaillons-nous ?</b> → <b>Où sont nos risques ?</b> → <b>Qu'allons-nous faire ?</b></p></S></>},
{id:"cif",title:"Comprendre la démarche CIF",summary:"Passer du fonctionnement réel à la maîtrise des risques.",category:"Comprendre",keywords:["cif","contrôle interne","maîtrise"],body:<><S><h3>Principe</h3><p>Le contrôle interne financier vise à donner une assurance raisonnable sur la qualité et la sécurité des processus financiers. PCIF Académie structure le diagnostic, la réponse aux risques et leur suivi dans le temps.</p></S></>},
{id:"campaign",title:"Comprendre une campagne",summary:"Périmètre annuel du diagnostic PCIF et de son suivi.",category:"Réaliser une action",keywords:["campagne","année","historique"],contexts:["home","pilotage"],body:<><S><h3>Une campagne</h3><p>Une campagne rassemble, pour un établissement et une période, les réponses au référentiel, l'organisation fonctionnelle, les processus, les risques, les actions et les indicateurs de pilotage.</p></S><S><h3>À retenir</h3><p>Conservez les campagnes clôturées : leur intérêt est aussi de rendre visible la trajectoire de maîtrise d'une année à l'autre.</p></S></>},
{id:"workshops",title:"Les quatre ateliers",summary:"Une progression collective en quatre temps d'environ une heure.",category:"Découvrir",keywords:["atelier","4 ateliers","animation"],contexts:["workshops"],auditor:false,body:<><S><h3>La progression</h3><ol><li><b>Qui fait quoi ?</b> — clarifier les acteurs et responsabilités.</li><li><b>Comment travaillons-nous ?</b> — décrire les processus et pratiques.</li><li><b>Où sont nos risques ?</b> — confronter le réel au référentiel.</li><li><b>Qu'allons-nous faire ?</b> — prioriser et suivre les actions.</li></ol></S></>},
{id:"onf",title:"Qui fait quoi ? — ONF",summary:"Décrire les acteurs, fonctions et responsabilités du processus financier.",category:"Comprendre",keywords:["onf","organigramme","acteur","responsabilité"],contexts:["onf"],body:<><S><h3>Comment l'utiliser ?</h3><p>L'organigramme fonctionnel ne reproduit pas l'organigramme hiérarchique : il matérialise qui intervient réellement dans les opérations et à quel titre.</p></S><S><h3>Auditeur</h3><p>Dans une mission d'audit, l'ONF est une pièce de compréhension du dispositif et reste en lecture seule.</p></S></>},
{id:"processes",title:"Processus et logigrammes",summary:"Lire la chaîne d'activités et ses points de maîtrise.",category:"Comprendre",keywords:["processus","logigramme","procédure","flux"],contexts:["processes"],body:<><S><h3>Processus, procédure, logigramme</h3><p>Le processus décrit une finalité et un enchaînement d'activités. Une procédure précise une manière de faire. Le logigramme rend le flux visible pour repérer responsabilités, contrôles, ruptures et interfaces.</p></S><S><h3>Auditeur</h3><p>Les logigrammes sont consultables en lecture seule dans le périmètre de la mission.</p></S></>},
{id:"reference",title:"Les 267 points du référentiel PCIF",summary:"Comprendre ce que mesure le référentiel et comment l'utiliser.",category:"Comprendre",keywords:["267","référentiel","question","contrôle"],contexts:["pilotage","workshops","audit"],body:<><S><h3>Le référentiel</h3><p>Les 267 points structurent l'auto-évaluation. Ils ne remplacent pas l'analyse du fonctionnement réel : une réponse doit pouvoir être reliée à une pratique, une preuve ou un dispositif de maîtrise.</p></S></>},
{id:"spheres",title:"Ordonnateur, comptable et mixte",summary:"Comprendre les trois sphères de réponse.",category:"Comprendre",keywords:["ordonnateur","comptable","mixte","synthèse"],body:<><S><h3>Trois regards</h3><p>La sphère ordonnateur porte le regard de l'établissement, la sphère comptable celui de l'agence comptable et la synthèse rapproche les deux lorsqu'un point appelle une lecture partagée.</p></S></>},
{id:"risks",title:"Comprendre les risques",summary:"Probabilité, gravité, niveau de risque et risque résiduel.",category:"Comprendre",keywords:["risque","probabilité","gravité","niveau de risque","résiduel","maîtrise"],contexts:["pilotage","audit"],body:<><S><h3>Niveau de risque</h3><p>Le niveau de risque résulte du croisement de la <b>probabilité</b> et de la <b>gravité</b> : <b>Probabilité × Gravité = Niveau de risque</b>, sur une échelle de 1 à 9.</p></S><S><h3>Risque résiduel</h3><p>C'est le risque restant après prise en compte des dispositifs de maîtrise existants. Une cotation n'a d'intérêt que si elle conduit à comprendre ce qui protège le processus et ce qui reste fragile.</p></S></>},
{id:"risk-map",title:"Comprendre la cartographie des processus",summary:"Lire la maîtrise et les zones d'attention par processus.",category:"Comprendre",keywords:["cartographie","processus","risque","couverture"],contexts:["processes","pilotage","audit"],body:<><S><h3>Comment la lire ?</h3><p>La cartographie agrège les informations du référentiel par processus. Utilisez-la pour localiser les sujets à examiner, puis revenez aux contrôles sous-jacents : l'agrégat est un signal, pas une conclusion.</p></S></>},
{id:"indicators",title:"Les quatre indicateurs d'évolution",summary:"Lire ensemble couverture, maîtrise, criticité et dynamique d'action.",category:"Comprendre",keywords:["indicateur","évolution","couverture","maîtrise","criticité"],contexts:["pilotage","processes"],body:<><S><h3>Une lecture plurielle</h3><p>Les indicateurs donnent plusieurs angles sur une même campagne. Ne réduisez pas l'analyse à un score global : regardez simultanément le niveau de renseignement, la maîtrise, les points critiques et le traitement par les actions.</p></S></>},
{id:"actions",title:"Construire un plan d'action",summary:"Transformer un diagnostic en actions vérifiables.",category:"Réaliser une action",keywords:["action","plan","responsable","échéance"],contexts:["pilotage"],body:<><S><h3>Une bonne action</h3><p>Elle répond à un risque identifié, possède un responsable, une échéance et un résultat observable. Évitez les formulations vagues comme « être vigilant » : elles ne permettent ni pilotage ni évaluation.</p></S></>},
{id:"actions-follow",title:"Suivre les actions",summary:"Passer de l'intention à l'amélioration constatée.",category:"Réaliser une action",keywords:["suivi","action","efficacité","échéance"],contexts:["pilotage"],body:<><S><h3>Réalisation ≠ efficacité</h3><p>Une action terminée n'est pas nécessairement efficace. Vérifiez ensuite si le risque ou la pratique ciblée a réellement évolué.</p></S></>},
{id:"audit",title:"Réaliser un audit",summary:"Examiner une campagne dans le périmètre et la période autorisés.",category:"Selon mon rôle",keywords:["audit","auditeur","mission","observation"],contexts:["audit"],body:<><S><h3>Principe</h3><p>La mission d'audit est bornée par une campagne, des dates et des droits. L'auditeur observe le dispositif existant sans participer aux ateliers ni modifier l'ONF ou les logigrammes.</p></S></>},
{id:"audit-access",title:"Habiliter temporairement un auditeur",summary:"Ouvrir un accès borné de date à date à une campagne.",category:"Réaliser une action",keywords:["habiliter","auditeur","date","accès"],contexts:["auditManagement","admin"],body:<><S><h3>Bon principe</h3><p>Accordez le périmètre strictement nécessaire, avec une date de début et une date de fin. La mission et le rôle permanent restent deux notions distinctes.</p></S></>},
{id:"auditor-rights",title:"Comprendre les droits de l'auditeur",summary:"Ce que l'auditeur peut consulter, observer et ce qu'il ne peut pas modifier.",category:"Selon mon rôle",keywords:["auditeur","droits","lecture seule","atelier"],contexts:["audit","onf","processes"],body:<><S><h3>Accès</h3><p>L'auditeur travaille uniquement dans le périmètre de sa mission. Il ne participe pas aux ateliers. L'ONF et les logigrammes sont en lecture seule. Les observations ne sont possibles que si la mission les autorise.</p></S></>},
{id:"cartopale",title:"Exporter vers Cartop@le",summary:"Produire le fichier d'échange depuis le tableau de bord de la campagne.",category:"Réaliser une action",keywords:["cartopale","export","fichier"],contexts:["pilotage"],body:<><S><h3>Export</h3><p>Utilisez l'export de la campagne considérée. Le fichier produit est destiné à l'import dans Cartop@le et doit refléter l'état courant de cette campagne.</p></S></>},
{id:"roles",title:"Rôles et habilitations",summary:"Comprendre qui voit quoi dans PCIF Académie.",category:"Selon mon rôle",keywords:["rôle","droit","habilitation","admin"],contexts:["admin"],body:<><S><h3>Principe du moindre privilège</h3><p>Les droits sont déterminés par le rôle, le rattachement et, pour l'audit, la mission temporaire. Une interface masquée ne remplace jamais un contrôle d'autorisation côté serveur.</p></S></>},
{id:"copilot",title:"Utiliser PCIF Copilot",summary:"Comprendre le futur assistant métier et ses limites.",category:"PCIF Copilot",keywords:["copilot","ia","assistant","source"],body:<><S><h3>Positionnement</h3><p>PCIF Copilot est conçu comme le domaine CIF d'EPLE Copilot. L'aide PCIF reste autonome : elle continue de fonctionner même si aucun service d'IA n'est disponible.</p></S><S><h3>Principe</h3><p>Le Copilot devra distinguer les sources documentaires, les données de campagne et ses propres analyses. Une suggestion ne devient jamais automatiquement une décision ou une écriture métier.</p></S></>},
{id:"glossary",title:"Glossaire CIF",summary:"Les termes essentiels du contrôle interne financier.",category:"Comprendre",keywords:["glossaire","définition","risque résiduel","contrôle"],body:<><S><h3>Termes clés</h3><dl className="help-glossary"><dt>Probabilité</dt><dd>Appréciation de la possibilité de survenue du risque, cotée de 1 à 3.</dd><dt>Gravité</dt><dd>Appréciation de l’importance des conséquences si le risque survient, cotée de 1 à 3.</dd><dt>Niveau de risque</dt><dd>Résultat du croisement Probabilité × Gravité, exprimé de 1 à 9.</dd><dt>Risque inhérent</dt><dd>Risque existant avant prise en compte des mesures de maîtrise.</dd><dt>Risque résiduel</dt><dd>Risque restant après prise en compte des dispositifs de maîtrise.</dd><dt>Dispositif de maîtrise</dt><dd>Organisation, contrôle ou pratique contribuant à réduire un risque.</dd><dt>ONF</dt><dd>Organigramme fonctionnel décrivant les acteurs et responsabilités d'un processus.</dd></dl></S></>},
{id:"faq",title:"Questions fréquentes",summary:"Réponses courtes aux questions d'usage les plus courantes.",category:"Résoudre un problème",keywords:["faq","question","problème"],body:<><S><h3>Pourquoi l'auditeur ne voit-il pas les ateliers ?</h3><p>Parce qu'il évalue le dispositif et ne participe pas à sa construction.</p><h3>Pourquoi l'ONF est-il en lecture seule pour lui ?</h3><p>Pour préserver la séparation entre observation et production du dispositif audité.</p><h3>PCIF Copilot pourra-t-il modifier mes données ?</h3><p>Le socle prévu privilégie la lecture et l'assistance. Toute écriture future devra être explicitement autorisée et validée par l'utilisateur.</p></S></>},
{id:"privacy",title:"Données, sécurité et traçabilité",summary:"Comprendre les principes retenus pour les accès et le futur Copilot.",category:"PCIF Copilot",keywords:["sécurité","données","confidentialité","trace"],body:<><S><h3>Principe</h3><p>Les services d'aide n'élargissent jamais les droits de l'utilisateur. Le futur Copilot devra passer par les services métier autorisés plutôt que par un accès direct aux données.</p></S></>},
{id:"sources",title:"Sources et limites de l'aide",summary:"Savoir distinguer aide applicative, référentiel et analyse.",category:"PCIF Copilot",keywords:["source","référentiel","limite","m96"],body:<><S><h3>Ne pas confondre</h3><p>L'aide explique l'application et la démarche. Le référentiel PCIF constitue une source métier distincte. Les textes réglementaires doivent être identifiés et versionnés séparément. Une future analyse Copilot devra toujours être présentée comme telle.</p></S></>}
];
const capabilities:Capability[]=[
{id:"pcif.help",title:"Aide PCIF Académie",description:"Recherche, aide contextuelle, glossaire et parcours guidés.",status:"AVAILABLE"},
{id:"pcif.reference",title:"Référentiel PCIF",description:"Mobiliser les 267 points comme source métier identifiable.",status:"AVAILABLE"},
{id:"pcif.campaign.read",title:"Analyse contextualisée d'une campagne",description:"Lire en contexte les résultats d'une campagne, sans écriture.",status:"IN_DEVELOPMENT"},
{id:"pcif.risk.analysis",title:"Analyse des risques",description:"Mettre en relation processus, contrôles, maîtrise et points d'attention.",status:"IN_DEVELOPMENT"},
{id:"pcif.action.suggest",title:"Assistance au plan d'action",description:"Préparer des pistes d'action soumises à validation humaine.",status:"PLANNED"},
{id:"pcif.audit.assist",title:"Assistance à l'audit",description:"Aider l'auditeur à préparer ses investigations dans son périmètre.",status:"PLANNED"},
{id:"pcif.multiCampaign.analysis",title:"Comparaison des campagnes",description:"Rendre visible la trajectoire de maîtrise dans le temps.",status:"PLANNED"},
{id:"pcif.agency.analysis",title:"Regard transversal agence",description:"Identifier des sujets communs sans classer les établissements.",status:"PLANNED"},
{id:"eple.copilot",title:"EPLE Copilot",description:"Étendre le même assistant à d'autres domaines EPLE Tools.",status:"PLANNED"}
];
const statusLabel:Record<CapabilityStatus,string>={AVAILABLE:"Disponible",IN_DEVELOPMENT:"En développement",PLANNED:"Envisagé"};
function userIsAuditor(me:Me){return !!me.user.isAuditor}
function roleIntro(me:Me){if(me.user.isAuditor)return "Votre aide privilégie l'audit et les contenus consultables en lecture seule.";if(me.user.isPlatformAdmin)return "Votre aide inclut la gouvernance de la plateforme et des habilitations.";if(me.agencies?.length)return "Votre aide met en avant le pilotage partagé et la coordination du groupement.";return "Votre aide met en avant la réalisation et le suivi de la campagne de l'établissement."}
export function HelpCenter({me,context,onClose}:{me:Me;context:HelpContext;onClose:()=>void}){
 const[query,setQuery]=useState(""),[selected,setSelected]=useState<string|null>(null),[mode,setMode]=useState<"help"|"future">("help"),[tour,setTour]=useState<number|null>(null);
 const visible=useMemo(()=>topics.filter(t=>t.auditor!==false||!userIsAuditor(me)),[me]);
 const recommended=visible.filter(t=>t.contexts?.includes(context)).slice(0,4);
 const filtered=useMemo(()=>{const q=query.trim().toLocaleLowerCase("fr");if(!q)return visible;return visible.filter(t=>[t.title,t.summary,t.category,...t.keywords].join(" ").toLocaleLowerCase("fr").includes(q))},[query,visible]);
 const topic=visible.find(t=>t.id===selected);
 const tours=[{title:"Découvrir PCIF Académie",steps:["Commencez par le tableau de bord : choisissez l'établissement et la campagne.","Les ateliers structurent le travail collectif en quatre temps.","L'ONF décrit qui fait quoi ; les processus décrivent comment le travail circule.","Le pilotage rapproche référentiel, risques, actions et évolution dans le temps."]},{title:"Réaliser ma première campagne",steps:["Ouvrez la campagne de l'établissement.","Clarifiez les acteurs et responsabilités dans l'ONF.","Décrivez les pratiques et processus avant de coter.","Répondez au référentiel à partir du fonctionnement réel.","Priorisez quelques actions vérifiables plutôt qu'une longue liste d'intentions."]},{title:"Analyser les risques",steps:["Repérez les processus qui appellent l'attention.","Descendez jusqu'aux contrôles qui expliquent le signal.","Identifiez les dispositifs de maîtrise déjà présents.","Distinguez risque constaté et interprétation.","Reliez le risque à une action et à un critère d'efficacité."]}];
 return <div className="help-overlay" role="dialog" aria-modal="true" aria-label="Centre d'aide"><aside className="help-drawer">
  <header className="help-header"><div><small>AIDE INTÉGRÉE</small><h2>{topic?topic.title:"PCIF Académie"}</h2></div><button className="help-close" onClick={onClose} aria-label="Fermer">×</button></header>
  {topic?<><button className="help-back" onClick={()=>setSelected(null)}>← Centre d'aide</button><div className="help-article"><p className="help-lead">{topic.summary}</p>{topic.body}<div className="help-related"><b>Voir aussi</b>{visible.filter(t=>t.id!==topic.id&&(t.category===topic.category||t.contexts?.some(c=>topic.contexts?.includes(c)))).slice(0,3).map(t=><button key={t.id} onClick={()=>setSelected(t.id)}>{t.title} →</button>)}</div></div></>:
  <><div className="help-tabs"><button className={mode==="help"?"active":""} onClick={()=>setMode("help")}>Aide</button><button className={mode==="future"?"active":""} onClick={()=>setMode("future")}>✦ PCIF Copilot · Future</button></div>
  {mode==="help"?<div className="help-body"><label className="help-search">⌕<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Comment pouvons-nous vous aider ?"/></label><p className="help-role-note">{roleIntro(me)}</p>
   {!query&&recommended.length>0&&<section><h3>Comprendre cet écran</h3><div className="help-recommend">{recommended.map(t=><button key={t.id} onClick={()=>setSelected(t.id)}><b>{t.title}</b><span>{t.summary}</span></button>)}</div></section>}
   {!query&&<section><h3>Visites guidées</h3><div className="help-tours">{tours.map((t,i)=><button key={t.title} onClick={()=>setTour(i)}>▶ {t.title}</button>)}</div>{tour!==null&&<div className="help-tour"><header><b>{tours[tour].title}</b><button onClick={()=>setTour(null)}>×</button></header><ol>{tours[tour].steps.map(s=><li key={s}>{s}</li>)}</ol><small>Parcours de découverte : aucune donnée n'est modifiée.</small></div>}</section>}
   <section><h3>{query?`${filtered.length} résultat${filtered.length>1?"s":""}`:"Toute l'aide"}</h3><div className="help-list">{filtered.map(t=><button key={t.id} onClick={()=>setSelected(t.id)}><span>{t.category}</span><b>{t.title}</b><small>{t.summary}</small></button>)}</div></section>
  </div>:<Future capabilities={capabilities}/>}</>}
 </aside></div>
}
function Future({capabilities}:{capabilities:Capability[]}){return <div className="help-body future"><div className="future-intro"><span>🔭 FUTURE</span><h3>PCIF Copilot — aujourd'hui & demain</h3><p>Cet espace rend visible la trajectoire fonctionnelle. Une capacité annoncée ici n'est pas nécessairement disponible dans l'application.</p></div><div className="future-legend"><span className="available">● Disponible</span><span className="development">◐ En développement</span><span className="planned">○ Envisagé</span></div><div className="capability-list">{capabilities.map(c=><article key={c.id}><i className={c.status.toLowerCase()}>{c.status==="AVAILABLE"?"●":c.status==="IN_DEVELOPMENT"?"◐":"○"}</i><div><small>{statusLabel[c.status]}</small><b>{c.title}</b><p>{c.description}</p></div></article>)}</div><section className="future-principle"><h3>Principe de conception</h3><p><b>Données → analyse → explication → suggestions → décision humaine.</b></p><p>PCIF Académie restera maître de ses données et de ses habilitations. L'aide fonctionne indépendamment du futur service EPLE Copilot.</p></section><section><h3>Trajectoire</h3><div className="future-roadmap"><b>Aujourd'hui</b><span>Aide intégrée · référentiel · contexte</span><b>Prochaine étape</b><span>Lecture de campagne · analyse contextualisée des risques</span><b>Ensuite</b><span>Plan d'action · audit · comparaison · groupement</span><b>Trajectoire</b><span>EPLE Copilot transverse aux outils</span></div></section></div>}
