import { PilotagePcif } from "./PilotagePcif";
import "bootstrap/dist/css/bootstrap.min.css";
import React,{useEffect,useMemo,useState} from "react";
import{createRoot}from"react-dom/client";
import{api,clearToken,getToken,setToken,type AdminUser,type Campaign,type Establishment,type Me,type Question}from"./api";
import { demoProfiles as demo } from "./demoProfiles";
import"./styles.css";

type View={kind:"home"}|{kind:"campaign";campaign:Campaign;establishment:Establishment}|{kind:"admin"};
const isDemo=import.meta.env.VITE_DEPLOYMENT_ENV==="demo";

function Logo(){return <div className="pcif-logo"><svg className="logo-shield" viewBox="0 0 40 46" aria-hidden="true"><path d="M20 2 36 9v12c0 11-6.7 19-16 23C10.7 40 4 32 4 21V9Z"/><path d="m12 22 5 5 11-12"/></svg><div><b>PCIF Académie</b><small>Pilotage du contrôle interne financier</small></div></div>}
function DemoBanner(){return isDemo?<div className="demo-banner" role="status"><strong>ENVIRONNEMENT DE DÉMONSTRATION</strong><span>Données réinitialisées automatiquement chaque heure</span></div>:null}
function App(){
 const[me,setMe]=useState<Me|null>(null),[view,setView]=useState<View>({kind:"home"}),[busy,setBusy]=useState(!!getToken());
 const[active,setActive]=useState<Establishment|null>(null),[ets,setEts]=useState<Establishment[]>([]);
 async function session(){setBusy(true);try{const m=await api.me(),e=await api.establishments();setMe(m);setEts(e);setActive(e[0]??null)}catch{clearToken();setMe(null)}finally{setBusy(false)}}
 useEffect(()=>{getToken()?session():setBusy(false)},[]);
 if(busy)return <><DemoBanner/><div className={`splash${isDemo?" demo-mode":""}`}><Logo/><span>Chargement…</span></div></>;
 if(!me)return new URLSearchParams(location.search).get("resetToken")?<ResetPassword/>:<Login onLogin={session}/>;
 const logout=()=>{clearToken();setMe(null);setView({kind:"home"})};
 return <div className={`pcif-app${isDemo?" demo-mode":""}`}>
   <DemoBanner/>
   <aside className="sidebar">
    <Logo/>
    <div className="profile"><small>Utilisateur connecté</small><strong>{me.user.displayName}</strong><span>{me.user.email}</span></div>
    <nav>
      <button className={view.kind==="home"?"active":""} onClick={()=>setView({kind:"home"})}>⌂ Tableau de bord</button>
      {me.user.isPlatformAdmin&&<button className={view.kind==="admin"?"active":""} onClick={()=>setView({kind:"admin"})}>⚙ Administration</button>}
    </nav>
    <div className="sidebar-foot"><button onClick={logout}>Déconnexion</button></div>
   </aside>
   <div className="workspace">
    <header className="topbar">
      <div className="context"><span>Établissement actif</span>
       <select value={active?.id??""} onChange={e=>{const x=ets.find(v=>v.id===e.target.value)||null;setActive(x);setView({kind:"home"})}} disabled={ets.length<=1}>
        {ets.map(e=><option key={e.id} value={e.id}>{e.name}</option>)}
       </select>
       {active&&<small>{active.uai} · {active.kind}</small>}
      </div>
      <div className="rolechips">{me.agencies.map(a=><span key={a.id}>{roleLabel(a.role)}</span>)}{me.establishments.filter(x=>x.id===active?.id).map(x=><span key={x.role}>{roleLabel(x.role)}</span>)}</div>
    </header>
    <main>
      {view.kind==="home"&&<Dashboard establishment={active} onOpen={(c,e)=>setView({kind:"campaign",campaign:c,establishment:e})}/>}
      {view.kind==="campaign"&&<PilotagePcif me={me} campaign={view.campaign} establishment={view.establishment} onBack={()=>setView({kind:"home"})}/>}
      {view.kind==="admin"&&<AdminHub establishments={ets}/>}
    </main>
   </div>
 </div>
}
function Login({onLogin}:{onLogin:()=>Promise<void>}){
 const[email,setEmail]=useState(demo[0]?.[1]??""),[password,setPassword]=useState(demo[0]?.[2]??""),[err,setErr]=useState(""),[forgot,setForgot]=useState(false),[sent,setSent]=useState(false);
 async function go(e:React.FormEvent){e.preventDefault();try{const r=await api.login(email,password);setToken(r.accessToken);await onLogin()}catch{setErr("Identifiants incorrects ou compte indisponible.")}}
 async function sendReset(e:React.FormEvent){e.preventDefault();await api.forgotPassword(email);setSent(true)}
 return <><DemoBanner/><div className={`login${isDemo?" demo-mode":""}`}><section><Logo/><h1>{forgot?"Mot de passe oublié":"Bienvenue"}</h1><p>{forgot?"Indiquez votre adresse. Si le compte existe, un lien valable une heure vous sera envoyé.":"Retrouvez PCIF Académie dans son environnement métier, désormais collaboratif et multi‑établissements."}</p>{forgot?<form onSubmit={sendReset}><label>Email<input type="email" required value={email} onChange={e=>setEmail(e.target.value)}/></label>{sent&&<div className="notice">Si cette adresse correspond à un compte actif, le courriel vient d’être envoyé.</div>}<button className="primary">Envoyer le lien</button><button type="button" className="link" onClick={()=>{setForgot(false);setSent(false)}}>Retour à la connexion</button></form>:<form onSubmit={go}><label>Email<input type="email" required value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Mot de passe<input type="password" required value={password} onChange={e=>setPassword(e.target.value)}/></label>{err&&<div className="error">{err}</div>}<button className="primary">Se connecter</button><button type="button" className="link" onClick={()=>setForgot(true)}>Mot de passe oublié ?</button></form>}</section>{isDemo&&!forgot&&<aside><b>Profils de démonstration</b>{demo.map(([l,m,p])=><button key={m} onClick={()=>{setEmail(m);setPassword(p)}}><span>{l}</span><small>{m}</small></button>)}</aside>}</div></>
}
function ResetPassword(){
 const token=new URLSearchParams(location.search).get("resetToken")||"",activation=new URLSearchParams(location.search).get("mode")==="activate";
 const[password,setPassword]=useState(""),[confirmPassword,setConfirmPassword]=useState(""),[state,setState]=useState<"form"|"done"|"error">("form"),[message,setMessage]=useState("");
 async function save(e:React.FormEvent){e.preventDefault();if(password.length<12){setMessage("Le mot de passe doit contenir au moins 12 caractères.");return}if(password!==confirmPassword){setMessage("Les deux mots de passe ne correspondent pas.");return}try{await api.resetPassword(token,password);setState("done");history.replaceState({},"",location.pathname)}catch{setState("error")}}
 return <><DemoBanner/><div className={`login login-single${isDemo?" demo-mode":""}`}><section><Logo/><h1>{activation?"Activer mon compte":"Nouveau mot de passe"}</h1>{state==="done"?<><div className="notice">Votre mot de passe est enregistré. Vous pouvez maintenant vous connecter.</div><button className="primary" onClick={()=>location.href="/"}>Se connecter</button></>:state==="error"?<><div className="error">Ce lien est invalide, expiré ou déjà utilisé.</div><button onClick={()=>location.href="/"}>Demander un nouveau lien</button></>:<form onSubmit={save}><p>Choisissez un mot de passe personnel d’au moins 12 caractères.</p><label>Nouveau mot de passe<input type="password" autoComplete="new-password" required value={password} onChange={e=>setPassword(e.target.value)}/></label><label>Confirmation<input type="password" autoComplete="new-password" required value={confirmPassword} onChange={e=>setConfirmPassword(e.target.value)}/></label>{message&&<div className="error">{message}</div>}<button className="primary">Enregistrer mon mot de passe</button></form>}</section></div></>
}
function Dashboard({establishment,onOpen}:{establishment:Establishment|null;onOpen:(c:Campaign,e:Establishment)=>void}){
 const[camps,setCamps]=useState<Campaign[]>([]);useEffect(()=>{establishment?api.campaigns(establishment.id).then(setCamps):setCamps([])},[establishment?.id]);
 if(!establishment)return <Empty text="Aucun établissement accessible."/>;
 return <><div className="hero"><div><small>PCIF Académie</small><h1>{establishment.name}</h1><p>Diagnostic, maîtrise des risques et plan d’action de l’établissement.</p></div><div className="pill">{establishment.uai}</div></div>
 <div className="tiles"><div><b>{camps.length}</b><span>Campagne(s)</span></div><div><b>{establishment.kind||"EPLE"}</b><span>Type</span></div><div><b>Multi</b><span>Travail collaboratif</span></div></div>
 <section className="panel"><h2>Campagnes PCIF</h2>{camps.map(c=><button className="campaign" key={c.id} onClick={()=>onOpen(c,establishment)}><div><span className="status">{c.status}</span><b>{c.label}</b><small>Référentiel {c.repository_version}{c.question_count ? ` · ${c.question_count} questions` : ""}</small></div><i>→</i></button>)}</section></>
}
function CampaignView({me,campaign,establishment,onBack}:{me:Me;campaign:Campaign;establishment:Establishment;onBack:()=>void}){
 const[questions,setQuestions]=useState<Question[]>([]),[domain,setDomain]=useState("TOUS"),[scope,setScope]=useState("TOUS");
 useEffect(()=>{api.questions(campaign.id).then(setQuestions)},[campaign.id]);
 const roles=me.establishments.filter(x=>x.id===establishment.id).map(x=>x.role),agency=me.agencies.map(x=>x.role),admin=!!me.user.isPlatformAdmin;
 const canO=admin||roles.some(r=>["HEAD","SECRETARY_GENERAL","CONTRIBUTOR"].includes(r));
 const canC=admin||roles.some(r=>["AGENCY_ACCOUNTANT","AGENCY_DEPUTY"].includes(r))||agency.some(r=>["AGENCY_ACCOUNTANT","AGENCY_DEPUTY"].includes(r));
 const domains=["TOUS",...Array.from(new Set(questions.map(q=>q.domain)))];
 const filtered=questions.filter(q=>(domain==="TOUS"||q.domain===domain)&&(scope==="TOUS"||q.responsibility===scope));
 return <><button className="back" onClick={onBack}>← Retour</button><div className="hero"><div><small>{campaign.status}</small><h1>{campaign.label}</h1><p>{establishment.name} · travail simultané ordonnateur / comptable.</p></div></div>
 <div className="scopebar"><select value={domain} onChange={e=>setDomain(e.target.value)}>{domains.map(d=><option key={d}>{d}</option>)}</select><button className={scope==="TOUS"?"active":""} onClick={()=>setScope("TOUS")}>Tous</button><button className={scope==="ORDONNATEUR"?"active o":""} onClick={()=>setScope("ORDONNATEUR")}>Ordonnateur</button><button className={scope==="COMPTABLE"?"active c":""} onClick={()=>setScope("COMPTABLE")}>Comptable</button><button className={scope==="MIXTE"?"active":""} onClick={()=>setScope("MIXTE")}>Mixte</button></div>
 <div className="questions">{filtered.map(q=><QuestionCard key={q.id} q={q} campaignId={campaign.id} canO={canO} canC={canC} onUpdate={x=>setQuestions(v=>v.map(a=>a.id===x.id?x:a))}/>)}</div></>
}
function QuestionCard({q,campaignId,canO,canC,onUpdate}:{q:Question;campaignId:string;canO:boolean;canC:boolean;onUpdate:(q:Question)=>void}){
 const spheres=q.responsibility==="MIXTE"?["ORDONNATEUR","COMPTABLE","SYNTHESE"] as const:[q.responsibility] as any;
 return <article className="questioncard"><div className="meta"><span>{q.domain}</span>{q.category&&<span>{q.category}</span>}<span className={q.responsibility==="ORDONNATEUR"?"o":q.responsibility==="COMPTABLE"?"c":""}>{q.responsibility}</span><span>★ {q.stars}/3</span><span>Poids {q.weight}</span>{q.is_key&&<span>◆ POINT CLÉ</span>}</div><h3>{q.label}</h3>{q.risk_label&&<p style={{color:"var(--muted)",marginTop:"-6px"}}>Risque : {q.risk_label}</p>}<div className="answergrid">{spheres.map((s:any)=><Answer key={s} q={q} sphere={s} campaignId={campaignId} editable={s==="ORDONNATEUR"?canO:s==="COMPTABLE"?canC:(canO||canC)} onUpdate={onUpdate}/>)}</div></article>
}
function Answer({q,sphere,campaignId,editable,onUpdate}:{q:Question;sphere:"ORDONNATEUR"|"COMPTABLE"|"SYNTHESE";campaignId:string;editable:boolean;onUpdate:(q:Question)=>void}){
 const ex=q.answers.find(a=>a.sphere===sphere);const[value,setValue]=useState<number|null>(ex?.value??null),[comment,setComment]=useState(ex?.comment??""),[state,setState]=useState("");
 async function save(){try{setState("Enregistrement…");const r=await api.saveAnswer(campaignId,q.id,{sphere,value,comment,version:ex?.version??0});onUpdate({...q,answers:[...q.answers.filter(a=>a.sphere!==sphere),{sphere,value:r.value,comment:r.comment,version:r.version,updatedAt:r.updated_at,updatedBy:""}]});setState("Enregistré")}catch(e:any){setState(e.status===409?"Conflit de version":"Erreur")}}
 return <div className="answerbox"><header><b>{sphereLabel(sphere)}</b>{!editable&&<small>Lecture seule</small>}</header><div className="scores">{[0,1,2,3].map(n=><button key={n} disabled={!editable} className={value===n?"active":""} onClick={()=>setValue(n)}>{n}</button>)}</div><textarea readOnly={!editable} value={comment} onChange={e=>setComment(e.target.value)} placeholder="Observation / preuve / action à prévoir…"/><footer><small>{state||ex?.updatedBy||""}</small>{editable&&<button className="primary" onClick={save}>Enregistrer</button>}</footer></div>
}
function AdminHub({establishments}:{establishments:Establishment[]}){
 const[tab,setTab]=useState<"users"|"ets"|"agencies">("users");
 return <><div className="admin-tabs"><button className={tab==="users"?"active":""} onClick={()=>setTab("users")}>Utilisateurs</button><button className={tab==="ets"?"active":""} onClick={()=>setTab("ets")}>Établissements</button><button className={tab==="agencies"?"active":""} onClick={()=>setTab("agencies")}>Agences comptables</button></div>{tab==="users"&&<AdminUsers establishments={establishments}/>} {tab==="ets"&&<AdminEstablishments/>} {tab==="agencies"&&<AdminAgencies/>}</>
}
function AdminEstablishments(){
 const[items,setItems]=useState<any[]>([]),[editing,setEditing]=useState<any|null>(null),[creating,setCreating]=useState(false);async function load(){setItems(await api.adminEstablishments())}useEffect(()=>{load()},[]);
 return <><div className="hero"><div><small>Administration</small><h1>Établissements</h1><p>Créer et maintenir les EPLE disponibles dans PCIF Académie.</p></div><button className="primary" onClick={()=>setCreating(true)}>+ Nouvel établissement</button></div><section className="panel"><table className="users"><thead><tr><th>UAI</th><th>Établissement</th><th>Type</th><th>Agence comptable</th><th>Statut</th><th></th></tr></thead><tbody>{items.map(e=><tr key={e.id}><td>{e.uai}</td><td><b>{e.name}</b></td><td>{e.kind||"—"}</td><td>{e.agency_name||"Non rattaché"}</td><td><span className={e.active?"ok":"off"}>{e.active?"Actif":"Suspendu"}</span></td><td><button onClick={()=>setEditing(e)}>Modifier</button></td></tr>)}</tbody></table></section>{(creating||editing)&&<EstablishmentModal item={editing} close={()=>{setCreating(false);setEditing(null)}} saved={async()=>{setCreating(false);setEditing(null);await load()}}/>}</>
}
function EstablishmentModal({item,close,saved}:any){const[uai,setUai]=useState(item?.uai||""),[name,setName]=useState(item?.name||""),[kind,setKind]=useState(item?.kind||"COLLEGE"),[active,setActive]=useState(item?.active??true),[err,setErr]=useState("");async function save(){try{const p={uai:uai.toUpperCase(),name,kind,active};if(item)await api.updateEstablishment(item.id,p);else await api.createEstablishment(p);await saved()}catch(e:any){setErr(e.message)}}return <div className="modal"><div><header><h2>{item?"Modifier":"Créer"} un établissement</h2><button onClick={close}>×</button></header><label>UAI<input maxLength={8} value={uai} onChange={e=>setUai(e.target.value.toUpperCase())}/></label><label>Nom<input value={name} onChange={e=>setName(e.target.value)}/></label><label>Type<select value={kind} onChange={e=>setKind(e.target.value)}><option>LPO</option><option>LP</option><option>LYCEE</option><option>COLLEGE</option><option>EREA</option><option>AUTRE</option></select></label>{item&&<label className="check"><input type="checkbox" checked={active} onChange={e=>setActive(e.target.checked)}/> Établissement actif</label>}{err&&<div className="error">{err}</div>}<footer><button onClick={close}>Annuler</button><button className="primary" onClick={save}>Enregistrer</button></footer></div></div>}
function AdminAgencies(){const[agencies,setAgencies]=useState<any[]>([]),[ets,setEts]=useState<any[]>([]),[editing,setEditing]=useState<any|null>(null),[creating,setCreating]=useState(false);async function load(){setAgencies(await api.adminAgencies());setEts(await api.adminEstablishments())}useEffect(()=>{load()},[]);return <><div className="hero"><div><small>Administration</small><h1>Agences comptables</h1><p>Définir l’établissement support et les EPLE rattachés à chaque agence.</p></div><button className="primary" onClick={()=>setCreating(true)}>+ Nouvelle agence</button></div><div className="agency-grid">{agencies.map(a=><article className="agency-card" key={a.id}><div><span className={a.active?"ok":"off"}>{a.active?"Active":"Inactive"}</span><h3>{a.name}</h3><p>Support : <b>{a.support_name}</b> · {a.support_uai}</p></div><strong>{a.establishments.length}<small> EPLE</small></strong><div className="agency-members">{a.establishments.map((e:any)=><span key={e.id}>{e.uai} · {e.name}</span>)}</div><button onClick={()=>setEditing(a)}>Configurer</button></article>)}</div>{(creating||editing)&&<AgencyModal item={editing} establishments={ets} close={()=>{setCreating(false);setEditing(null)}} saved={async()=>{setCreating(false);setEditing(null);await load()}}/>}</>}
function AgencyModal({item,establishments,close,saved}:any){const[name,setName]=useState(item?.name||""),[support,setSupport]=useState(item?.support_establishment_id||establishments[0]?.id||""),[members,setMembers]=useState<string[]>(item?.establishments?.map((e:any)=>e.id)||[]),[active,setActive]=useState(item?.active??true),[err,setErr]=useState("");function toggle(id:string){setMembers(m=>m.includes(id)?m.filter(x=>x!==id):[...m,id])}async function save(){try{const payload={name,supportEstablishmentId:support,establishmentIds:Array.from(new Set([support,...members])),active};if(item)await api.updateAgency(item.id,payload);else await api.createAgency(payload);await saved()}catch(e:any){setErr(e.message)}}return <div className="modal"><div className="agency-modal"><header><h2>{item?"Configurer":"Créer"} une agence comptable</h2><button onClick={close}>×</button></header><label>Nom<input value={name} onChange={e=>setName(e.target.value)}/></label><label>Établissement support<select value={support} onChange={e=>setSupport(e.target.value)}>{establishments.filter((e:any)=>e.active).map((e:any)=><option key={e.id} value={e.id}>{e.uai} · {e.name}</option>)}</select></label><h3>Établissements rattachés</h3><div className="member-picker">{establishments.filter((e:any)=>e.active).map((e:any)=><label key={e.id}><input type="checkbox" checked={e.id===support||members.includes(e.id)} disabled={e.id===support} onChange={()=>toggle(e.id)}/><span>{e.uai}<b>{e.name}</b></span></label>)}</div>{item&&<label className="check"><input type="checkbox" checked={active} onChange={e=>setActive(e.target.checked)}/> Agence active</label>}{err&&<div className="error">{err}</div>}<footer><button onClick={close}>Annuler</button><button className="primary" onClick={save}>Enregistrer</button></footer></div></div>}
function AdminUsers({establishments}:{establishments:Establishment[]}){
 const[users,setUsers]=useState<AdminUser[]>([]),[roles,setRoles]=useState<any[]>([]),[editing,setEditing]=useState<AdminUser|null>(null),[creating,setCreating]=useState(false),[msg,setMsg]=useState("");
 async function load(){setUsers(await api.adminUsers());setRoles(await api.adminRoles())} useEffect(()=>{load()},[]);
 async function del(u:AdminUser){if(!confirm(`Supprimer ${u.display_name} ? Cette suppression est logique et conserve l'audit.`))return;await api.deleteUser(u.id);await load()}
 async function suspend(u:AdminUser){await api.updateUser(u.id,{email:u.email,displayName:u.display_name,active:!u.active,assignments:u.assignments.map(a=>({establishmentId:a.establishmentId,roleCode:a.roleCode}))});await load()}
 return <><div className="hero"><div><small>Administration</small><h1>Utilisateurs</h1><p>Un utilisateur possède une adresse email valide et au moins un rattachement établissement + rôle.</p></div><button className="primary" onClick={()=>setCreating(true)}>+ Nouvel utilisateur</button></div>
 {msg&&<div className="notice">{msg}</div>}<section className="panel"><table className="users"><thead><tr><th>Utilisateur</th><th>Statut</th><th>Rattachements</th><th></th></tr></thead><tbody>{users.map(u=><tr key={u.id}><td><b>{u.display_name}</b><small>{u.email}{u.is_platform_admin?" · ADMIN":""}</small></td><td><span className={u.active?"ok":"off"}>{u.active?"Actif":"Suspendu"}</span></td><td>{u.assignments.map((a,i)=><span className="assignment" key={i}>{a.establishmentName} · {roleLabel(a.roleCode)}</span>)}</td><td className="actions"><button onClick={()=>setEditing(u)}>Modifier</button>{!u.is_platform_admin&&<><button onClick={()=>suspend(u)}>{u.active?"Suspendre":"Réactiver"}</button><button className="danger" onClick={()=>del(u)}>Supprimer</button></>}</td></tr>)}</tbody></table></section>
 {(editing||creating)&&<UserModal user={editing} establishments={establishments} roles={roles} onClose={()=>{setEditing(null);setCreating(false)}} onSaved={async(emailSent)=>{setEditing(null);setCreating(false);await load();if(emailSent!==undefined)setMsg(emailSent?"Compte créé : le courriel d’activation a été envoyé.":"Compte créé, mais le courriel d’activation n’a pas pu être envoyé. Vérifiez la configuration SMTP puis utilisez « mot de passe oublié ».")}}/>}</>
}
function UserModal({user,establishments,roles,onClose,onSaved}:{user:AdminUser|null;establishments:Establishment[];roles:any[];onClose:()=>void;onSaved:(emailSent?:boolean)=>void}){
 const[email,setEmail]=useState(user?.email??""),[name,setName]=useState(user?.display_name??""),[active,setActive]=useState(user?.active??true),[assign,setAssign]=useState<any[]>(user?.assignments.map(a=>({establishmentId:a.establishmentId,roleCode:a.roleCode}))??[{establishmentId:establishments[0]?.id??"",roleCode:"SECRETARY_GENERAL"}]),[err,setErr]=useState("");
 function patch(i:number,k:string,v:string){setAssign(a=>a.map((x,j)=>j===i?{...x,[k]:v}:x))}
 async function save(){try{if(!email.includes("@"))throw new Error("Email invalide");const payload={email,displayName:name,active,assignments:assign};if(user)await api.updateUser(user.id,payload);else{const r:any=await api.createUser(payload);await onSaved(!!r.emailSent);return}await onSaved()}catch(e:any){setErr(e.message||"Erreur")}}
 return <div className="modal"><div><header><h2>{user?"Modifier":"Créer"} un utilisateur</h2><button onClick={onClose}>×</button></header><label>Nom<input value={name} onChange={e=>setName(e.target.value)}/></label><label>Email<input type="email" required value={email} onChange={e=>setEmail(e.target.value)}/></label>{user&&<label className="check"><input type="checkbox" checked={active} onChange={e=>setActive(e.target.checked)}/> Compte actif</label>}<h3>Établissements et rôles</h3>{assign.map((a,i)=><div className="assignmentrow" key={i}><select value={a.establishmentId} onChange={e=>patch(i,"establishmentId",e.target.value)}>{establishments.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><select value={a.roleCode} onChange={e=>patch(i,"roleCode",e.target.value)}>{roles.map(r=><option key={r.code} value={r.code}>{r.label}</option>)}</select>{assign.length>1&&<button onClick={()=>setAssign(x=>x.filter((_,j)=>j!==i))}>−</button>}</div>)}<button className="link" onClick={()=>setAssign(x=>[...x,{establishmentId:establishments[0]?.id??"",roleCode:"READER"}])}>+ Ajouter un établissement</button>{err&&<div className="error">{err}</div>}<footer><button onClick={onClose}>Annuler</button><button className="primary" onClick={save}>Enregistrer</button></footer></div></div>
}
function Empty({text}:{text:string}){return <div className="empty">{text}</div>}function sphereLabel(s:string){return s==="ORDONNATEUR"?"Ordonnateur":s==="COMPTABLE"?"Comptable":"Synthèse"}function roleLabel(r:string){return({AGENCY_ACCOUNTANT:"Agent comptable",AGENCY_DEPUTY:"Fondé de pouvoir",HEAD:"Chef d’établissement",SECRETARY_GENERAL:"Secrétaire général",CONTRIBUTOR:"Contributeur",READER:"Lecteur",AUDITOR:"Auditeur",PLATFORM_ADMIN:"Administrateur"} as any)[r]||r}
createRoot(document.getElementById("root")!).render(<App/>);
