import type { FastifyInstance } from "fastify";
import { z } from "zod";
import { pool } from "./db.js";
import { requireUser } from "./auth.js";
import { isPlatformAdmin } from "./access.js";

const themeCounts=[[1,"Images",9],[2,"Cadres",2],[3,"Couleurs",3],[4,"Multimédia",13],[5,"Tableaux",8],[6,"Liens",2],[7,"Scripts",5],[8,"Éléments obligatoires",10],[9,"Structuration de l’information",4],[10,"Présentation de l’information",14],[11,"Formulaires",13],[12,"Navigation",11],[13,"Consultation",12]] as const;
const criteria=themeCounts.flatMap(([n,theme,count])=>Array.from({length:count},(_,i)=>({code:`${n}.${i+1}`,theme,label:`Critère ${n}.${i+1}`,officialUrl:`https://accessibilite.numerique.gouv.fr/methode/criteres-et-tests/#crit-${n}-${i+1}`})));
async function admin(req:any,reply:any){const u=await requireUser(req);if(!(await isPlatformAdmin(u.sub))){reply.code(403).send({error:"FORBIDDEN"});return null}return u}
function stats(results:any[]){const c=results.filter(x=>x.status==='C').length,nc=results.filter(x=>x.status==='NC').length,na=results.filter(x=>x.status==='NA').length,done=c+nc+na,applicable=c+nc;return{c,nc,na,done,total:106,rate:done===106&&applicable?Math.round(c/applicable*1000)/10:null,blocking:results.filter(x=>x.status==='NC'&&x.impact==='BLOCKING').length,major:results.filter(x=>x.status==='NC'&&x.impact==='MAJOR').length,minor:results.filter(x=>x.status==='NC'&&x.impact==='MINOR').length,easy:results.filter(x=>x.status==='NC'&&x.easy_fix).length}}
export async function registerAccessibility(app:FastifyInstance){
 app.get('/api/admin/accessibility/criteria',async(req,reply)=>{if(!await admin(req,reply))return;return criteria});
 app.get('/api/admin/accessibility/audits',async(req,reply)=>{if(!await admin(req,reply))return;const {rows}=await pool.query(`SELECT a.*,(SELECT count(*)::int FROM accessibility_results r WHERE r.audit_id=a.id AND r.status IS NOT NULL) completed FROM accessibility_audits a ORDER BY created_at DESC`);return rows});
 app.post('/api/admin/accessibility/audits',async(req,reply)=>{const u=await admin(req,reply);if(!u)return;const p=z.object({title:z.string().min(3),applicationVersion:z.string().min(1)}).parse(req.body);const {rows}=await pool.query(`INSERT INTO accessibility_audits(title,application_version,created_by) VALUES($1,$2,$3) RETURNING *`,[p.title,p.applicationVersion,u.sub]);return reply.code(201).send(rows[0])});
 app.get('/api/admin/accessibility/audits/:id',async(req,reply)=>{if(!await admin(req,reply))return;const id=(req.params as any).id;const a=await pool.query(`SELECT * FROM accessibility_audits WHERE id=$1`,[id]);if(!a.rowCount)return reply.code(404).send({error:'NOT_FOUND'});const r=await pool.query(`SELECT * FROM accessibility_results WHERE audit_id=$1`,[id]);return{audit:a.rows[0],criteria,results:r.rows,stats:stats(r.rows)}});
 app.put('/api/admin/accessibility/audits/:id/results/:code',async(req,reply)=>{if(!await admin(req,reply))return;const {id,code}=req.params as any;const p=z.object({status:z.enum(['C','NC','NA']),errorTitle:z.string().optional(),errorDescription:z.string().optional(),recommendation:z.string().optional(),impact:z.enum(['BLOCKING','MAJOR','MINOR']).nullable().optional(),easyFix:z.boolean().default(false),naJustification:z.string().optional(),evidence:z.string().optional()}).parse(req.body);if(p.status==='NC'&&(!p.errorTitle?.trim()||!p.errorDescription?.trim()||!p.recommendation?.trim()||!p.impact))return reply.code(400).send({error:'NC_DETAILS_REQUIRED'});if(p.status==='NA'&&!p.naJustification?.trim())return reply.code(400).send({error:'NA_JUSTIFICATION_REQUIRED'});const {rows}=await pool.query(`INSERT INTO accessibility_results(audit_id,criterion_code,status,error_title,error_description,recommendation,impact,easy_fix,na_justification,evidence) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) ON CONFLICT(audit_id,criterion_code) DO UPDATE SET status=EXCLUDED.status,error_title=EXCLUDED.error_title,error_description=EXCLUDED.error_description,recommendation=EXCLUDED.recommendation,impact=EXCLUDED.impact,easy_fix=EXCLUDED.easy_fix,na_justification=EXCLUDED.na_justification,evidence=EXCLUDED.evidence,updated_at=now() RETURNING *`,[id,code,p.status,p.errorTitle||null,p.errorDescription||null,p.recommendation||null,p.impact||null,p.easyFix,p.naJustification||null,p.evidence||null]);return rows[0]});
 app.post('/api/admin/accessibility/audits/:id/close',async(req,reply)=>{if(!await admin(req,reply))return;const id=(req.params as any).id;const n=await pool.query(`SELECT count(*)::int n FROM accessibility_results WHERE audit_id=$1 AND status IS NOT NULL`,[id]);if(n.rows[0].n!==106)return reply.code(409).send({error:'AUDIT_INCOMPLETE',completed:n.rows[0].n});const {rows}=await pool.query(`UPDATE accessibility_audits SET status='CLOSED',closed_at=now() WHERE id=$1 RETURNING *`,[id]);return rows[0]});
 app.post('/api/admin/accessibility/audits/:id/publish',async(req,reply)=>{const u=await admin(req,reply);if(!u)return;const id=(req.params as any).id;const a=await pool.query(`SELECT * FROM accessibility_audits WHERE id=$1 AND status='CLOSED'`,[id]);if(!a.rowCount)return reply.code(409).send({error:'AUDIT_NOT_CLOSED'});const r=await pool.query(`SELECT * FROM accessibility_results WHERE audit_id=$1 ORDER BY split_part(criterion_code,'.',1)::int,split_part(criterion_code,'.',2)::int`,[id]);const st=stats(r.rows);const snapshot={audit:a.rows[0],criteria,results:r.rows,stats:st};await pool.query(`UPDATE accessibility_reports SET is_current=false WHERE is_current=true`);const slug=`rgaa-${new Date().toISOString().slice(0,10)}-${id.slice(0,8)}`;const {rows}=await pool.query(`INSERT INTO accessibility_reports(audit_id,slug,snapshot,published_by) VALUES($1,$2,$3,$4) RETURNING id,slug,published_at,is_current`,[id,slug,JSON.stringify(snapshot),u.sub]);return rows[0]});
 app.get('/api/admin/accessibility/reports',async(req,reply)=>{if(!await admin(req,reply))return;const {rows}=await pool.query(`SELECT r.id,r.slug,r.published_at,r.unpublished_at,r.is_current,a.title,a.application_version FROM accessibility_reports r JOIN accessibility_audits a ON a.id=r.audit_id ORDER BY r.published_at DESC`);return rows});
 app.post('/api/admin/accessibility/reports/:id/unpublish',async(req,reply)=>{if(!await admin(req,reply))return;await pool.query(`UPDATE accessibility_reports SET is_current=false,unpublished_at=now() WHERE id=$1`,[(req.params as any).id]);return{ok:true}});
 app.get('/api/accessibility/report/current',async()=>{const {rows}=await pool.query(`SELECT slug,published_at,snapshot FROM accessibility_reports WHERE is_current=true AND unpublished_at IS NULL ORDER BY published_at DESC LIMIT 1`);return rows[0]||null});
 app.get('/api/accessibility/reports/:slug',async(req,reply)=>{const {rows}=await pool.query(`SELECT slug,published_at,snapshot FROM accessibility_reports WHERE slug=$1 AND unpublished_at IS NULL`,[(req.params as any).slug]);if(!rows.length)return reply.code(404).send({error:'NOT_FOUND'});return rows[0]});
}
