import type { FastifyInstance } from "fastify";
import { z } from "zod";
import { pool } from "./db.js";
import { requireUser } from "./auth.js";
import { isPlatformAdmin } from "./access.js";
import { readFileSync } from "node:fs";

const themeCounts=[[1,"Images",9],[2,"Cadres",2],[3,"Couleurs",3],[4,"Multimédia",13],[5,"Tableaux",8],[6,"Liens",2],[7,"Scripts",5],[8,"Éléments obligatoires",10],[9,"Structuration de l’information",4],[10,"Présentation de l’information",14],[11,"Formulaires",13],[12,"Navigation",11],[13,"Consultation",12]] as const;
const criteria=themeCounts.flatMap(([n,theme,count])=>Array.from({length:count},(_,i)=>({code:`${n}.${i+1}`,theme,label:`Critère ${n}.${i+1}`,officialUrl:`https://accessibilite.numerique.gouv.fr/methode/criteres-et-tests/#crit-${n}-${i+1}`})));

const publicDocs:any={schema:{title:"Schéma pluriannuel d’accessibilité",file:"accessibilite-schema-pluriannuel.md"},"plan-2026":{title:"Plan d’actions accessibilité 2026",file:"accessibilite-plan-actions-2026.md"}};
function crc32(buf:Buffer){let c=0xffffffff;for(const b of buf){c^=b;for(let k=0;k<8;k++)c=(c>>>1)^((c&1)?0xedb88320:0)}return(c^0xffffffff)>>>0}
function zipStore(files:{name:string,data:Buffer}[]){const locals:Buffer[]=[],centrals:Buffer[]=[];let off=0;for(const f of files){const name=Buffer.from(f.name),data=f.data,crc=crc32(data);const lh=Buffer.alloc(30);lh.writeUInt32LE(0x04034b50,0);lh.writeUInt16LE(20,4);lh.writeUInt16LE(0,6);lh.writeUInt16LE(0,8);lh.writeUInt32LE(crc,14);lh.writeUInt32LE(data.length,18);lh.writeUInt32LE(data.length,22);lh.writeUInt16LE(name.length,26);const local=Buffer.concat([lh,name,data]);locals.push(local);const ch=Buffer.alloc(46);ch.writeUInt32LE(0x02014b50,0);ch.writeUInt16LE(20,4);ch.writeUInt16LE(20,6);ch.writeUInt32LE(crc,16);ch.writeUInt32LE(data.length,20);ch.writeUInt32LE(data.length,24);ch.writeUInt16LE(name.length,28);ch.writeUInt32LE(off,42);centrals.push(Buffer.concat([ch,name]));off+=local.length}const central=Buffer.concat(centrals),end=Buffer.alloc(22);end.writeUInt32LE(0x06054b50,0);end.writeUInt16LE(files.length,8);end.writeUInt16LE(files.length,10);end.writeUInt32LE(central.length,12);end.writeUInt32LE(off,16);return Buffer.concat([...locals,central,end])}
function xml(s:string){return s.replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;")}
function markdownToOdt(title:string,md:string){const paras=md.replace(/\r/g,'').split('\n').filter(x=>x.trim()).map(line=>{const h=line.match(/^(#{1,4})\s+(.*)$/);const txt=(h?h[2]:line.replace(/^[-*]\s+/,"• ")).replace(/\*\*/g,'').replace(/`/g,'');return `<text:p text:style-name="${h?'Heading':'Text'}">${xml(txt)}</text:p>`}).join('');const content=`<?xml version="1.0" encoding="UTF-8"?><office:document-content xmlns:office="urn:oasis:names:tc:opendocument:xmlns:office:1.0" xmlns:text="urn:oasis:names:tc:opendocument:xmlns:text:1.0" office:version="1.2"><office:automatic-styles/><office:body><office:text><text:h text:outline-level="1">${xml(title)}</text:h>${paras}</office:text></office:body></office:document-content>`;const manifest=`<?xml version="1.0" encoding="UTF-8"?><manifest:manifest xmlns:manifest="urn:oasis:names:tc:opendocument:xmlns:manifest:1.0" manifest:version="1.2"><manifest:file-entry manifest:full-path="/" manifest:media-type="application/vnd.oasis.opendocument.text"/><manifest:file-entry manifest:full-path="content.xml" manifest:media-type="text/xml"/></manifest:manifest>`;return zipStore([{name:'mimetype',data:Buffer.from('application/vnd.oasis.opendocument.text')},{name:'content.xml',data:Buffer.from(content)},{name:'META-INF/manifest.xml',data:Buffer.from(manifest)}])}

async function admin(req:any,reply:any){const u=await requireUser(req);if(!(await isPlatformAdmin(u.sub))){reply.code(403).send({error:"FORBIDDEN"});return null}return u}
function stats(results:any[]){const c=results.filter(x=>x.status==='C').length,nc=results.filter(x=>x.status==='NC').length,na=results.filter(x=>x.status==='NA').length,done=c+nc+na,applicable=c+nc;return{c,nc,na,done,total:106,rate:done===106&&applicable?Math.round(c/applicable*1000)/10:null,blocking:results.filter(x=>x.status==='NC'&&x.impact==='BLOCKING').length,major:results.filter(x=>x.status==='NC'&&x.impact==='MAJOR').length,minor:results.filter(x=>x.status==='NC'&&x.impact==='MINOR').length,easy:results.filter(x=>x.status==='NC'&&x.easy_fix).length}}

function htmlEscape(value:any){return String(value??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;')}
function publicReportHtml(row:any){
 let snap:any=row.snapshot; try{if(typeof snap==='string')snap=JSON.parse(snap)}catch{snap=null}
 if(!snap?.stats) return null;
 const st=snap.stats, audit=snap.audit||{}, results=Array.isArray(snap.results)?snap.results:[], crit=Array.isArray(snap.criteria)?snap.criteria:[];
 const themes=new Map<string,{c:number,nc:number,na:number}>();
 for(const c of crit){const k=c.theme||'Autre';if(!themes.has(k))themes.set(k,{c:0,nc:0,na:0});const x=results.find((r:any)=>r.criterion_code===c.code);const t=themes.get(k)!;if(x?.status==='C')t.c++;else if(x?.status==='NC')t.nc++;else if(x?.status==='NA')t.na++}
 const themeRows=[...themes.entries()].map(([k,v])=>`<tr><th>${htmlEscape(k)}</th><td>${v.c}</td><td>${v.nc}</td><td>${v.na}</td></tr>`).join('');
 const findings=results.filter((x:any)=>x.status==='NC').map((x:any)=>`<article class="finding"><h3>${htmlEscape(x.criterion_code)} — ${htmlEscape(x.error_title||'Non-conformité')}</h3><p><strong>Impact : ${x.impact==='BLOCKING'?'Bloquant':x.impact==='MAJOR'?'Majeur':'Mineur'}</strong>${x.easy_fix?' · Facile à corriger':''}</p><p>${htmlEscape(x.error_description)}</p><h4>Correction recommandée</h4><p>${htmlEscape(x.recommendation)}</p></article>`).join('')||'<p>Aucune non-conformité déclarée.</p>';
 const status=st.rate===100?'totalement conforme':st.rate>=50?'partiellement conforme':'non conforme';
 return `<!doctype html><html lang="fr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Rapport RGAA — PCIF Académie</title><style>body{font-family:system-ui,sans-serif;max-width:1100px;margin:auto;padding:32px;color:#172033}header{display:flex;justify-content:space-between;gap:20px;align-items:center;border-bottom:1px solid #d8dee9;padding-bottom:18px}a{color:#155eef}.summary{display:grid;grid-template-columns:repeat(3,1fr);gap:16px;margin:24px 0}.card{border:1px solid #d8dee9;border-radius:12px;padding:18px}.card strong{display:block;font-size:2rem}.bad{border-color:#f1aeb5}.good{border-color:#a3cfbb}table{border-collapse:collapse;width:100%}th,td{border-bottom:1px solid #ddd;padding:10px;text-align:left}.finding{border-left:4px solid #b42318;padding:4px 18px;margin:22px 0;background:#fff8f7}.actions{display:flex;gap:12px;flex-wrap:wrap}.button{display:inline-block;border:1px solid #155eef;border-radius:8px;padding:9px 12px;text-decoration:none;background:#155eef;color:white}@media(max-width:700px){.summary{grid-template-columns:1fr}}@media print{.actions{display:none}body{max-width:none;padding:0}}</style></head><body><header><div><strong>PCIF Académie</strong><div>Rapport public d’accessibilité</div></div><div class="actions"><a href="/?legal=accessibilite">Accessibilité</a><button class="button" onclick="window.print()">Imprimer / PDF</button></div></header><main><h1>Audit d’accessibilité RGAA ${htmlEscape(audit.rgaa_version||'4.1.2')}</h1><p>Version auditée : <strong>${htmlEscape(audit.application_version||'—')}</strong> · Rapport publié le ${new Date(row.published_at).toLocaleDateString('fr-FR')}.</p><p>État : <strong>Accessibilité : ${status}</strong>.</p><section class="summary"><div class="card"><strong>${st.rate??'—'}${st.rate!=null?' %':''}</strong>Taux global de conformité</div><div class="card bad"><strong>${st.nc??0}</strong>Critères non conformes · ${st.blocking??0} bloquant(s)</div><div class="card good"><strong>${st.c??0}</strong>Critères conformes</div></section><h2>Répartition par thématiques</h2><table><thead><tr><th>Thématique</th><th>C</th><th>NC</th><th>NA</th></tr></thead><tbody>${themeRows}</tbody></table><h2>Détails des non-conformités</h2>${findings}</main></body></html>`
}

export async function registerAccessibility(app:FastifyInstance){
 app.get('/api/accessibility/documents/:id.odt',async(req,reply)=>{const id=(req.params as any).id,d=publicDocs[id];if(!d)return reply.code(404).send({error:'NOT_FOUND'});try{const md=readFileSync(`web/public/docs/${d.file}`,'utf8'),odt=markdownToOdt(d.title,md);return reply.header('Content-Type','application/vnd.oasis.opendocument.text').header('Content-Disposition',`attachment; filename="${id}.odt"`).send(odt)}catch{return reply.code(404).send({error:'DOCUMENT_NOT_FOUND'})}});
 app.get('/api/admin/accessibility/criteria',async(req,reply)=>{if(!await admin(req,reply))return;return criteria});
 app.get('/api/admin/accessibility/audits',async(req,reply)=>{if(!await admin(req,reply))return;const {rows}=await pool.query(`SELECT a.*,(SELECT count(*)::int FROM accessibility_results r WHERE r.audit_id=a.id AND r.status IS NOT NULL) completed FROM accessibility_audits a ORDER BY created_at DESC`);return rows});
 app.post('/api/admin/accessibility/audits',async(req,reply)=>{const u=await admin(req,reply);if(!u)return;const p=z.object({title:z.string().min(3),applicationVersion:z.string().min(1)}).parse(req.body);const {rows}=await pool.query(`INSERT INTO accessibility_audits(title,application_version,created_by) VALUES($1,$2,$3) RETURNING *`,[p.title,p.applicationVersion,u.sub]);return reply.code(201).send(rows[0])});
 app.get('/api/admin/accessibility/audits/:id',async(req,reply)=>{if(!await admin(req,reply))return;const id=(req.params as any).id;const a=await pool.query(`SELECT * FROM accessibility_audits WHERE id=$1`,[id]);if(!a.rowCount)return reply.code(404).send({error:'NOT_FOUND'});const r=await pool.query(`SELECT * FROM accessibility_results WHERE audit_id=$1`,[id]);return{audit:a.rows[0],criteria,results:r.rows,stats:stats(r.rows)}});
 app.put('/api/admin/accessibility/audits/:id/results/:code',async(req,reply)=>{if(!await admin(req,reply))return;const {id,code}=req.params as any;const p=z.object({status:z.enum(['C','NC','NA']),errorTitle:z.string().optional(),errorDescription:z.string().optional(),recommendation:z.string().optional(),impact:z.enum(['BLOCKING','MAJOR','MINOR']).nullable().optional(),easyFix:z.boolean().default(false),naJustification:z.string().optional(),evidence:z.string().optional()}).parse(req.body);if(p.status==='NC'&&(!p.errorTitle?.trim()||!p.errorDescription?.trim()||!p.recommendation?.trim()||!p.impact))return reply.code(400).send({error:'NC_DETAILS_REQUIRED'});if(p.status==='NA'&&!p.naJustification?.trim())return reply.code(400).send({error:'NA_JUSTIFICATION_REQUIRED'});const {rows}=await pool.query(`INSERT INTO accessibility_results(audit_id,criterion_code,status,error_title,error_description,recommendation,impact,easy_fix,na_justification,evidence) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) ON CONFLICT(audit_id,criterion_code) DO UPDATE SET status=EXCLUDED.status,error_title=EXCLUDED.error_title,error_description=EXCLUDED.error_description,recommendation=EXCLUDED.recommendation,impact=EXCLUDED.impact,easy_fix=EXCLUDED.easy_fix,na_justification=EXCLUDED.na_justification,evidence=EXCLUDED.evidence,updated_at=now() RETURNING *`,[id,code,p.status,p.errorTitle||null,p.errorDescription||null,p.recommendation||null,p.impact||null,p.easyFix,p.naJustification||null,p.evidence||null]);return rows[0]});
 app.post('/api/admin/accessibility/audits/:id/close',async(req,reply)=>{if(!await admin(req,reply))return;const id=(req.params as any).id;const n=await pool.query(`SELECT count(*)::int n FROM accessibility_results WHERE audit_id=$1 AND status IS NOT NULL`,[id]);if(n.rows[0].n!==106)return reply.code(409).send({error:'AUDIT_INCOMPLETE',completed:n.rows[0].n});const {rows}=await pool.query(`UPDATE accessibility_audits SET status='CLOSED',closed_at=now() WHERE id=$1 RETURNING *`,[id]);return rows[0]});
 app.post('/api/admin/accessibility/audits/:id/publish',async(req,reply)=>{const u=await admin(req,reply);if(!u)return;const id=(req.params as any).id;const a=await pool.query(`SELECT * FROM accessibility_audits WHERE id=$1 AND status='CLOSED'`,[id]);if(!a.rowCount)return reply.code(409).send({error:'AUDIT_NOT_CLOSED'});const r=await pool.query(`SELECT * FROM accessibility_results WHERE audit_id=$1 ORDER BY split_part(criterion_code,'.',1)::int,split_part(criterion_code,'.',2)::int`,[id]);const st=stats(r.rows);const snapshot={audit:a.rows[0],criteria,results:r.rows,stats:st};await pool.query(`UPDATE accessibility_reports SET is_current=false WHERE is_current=true`);const slug=`rgaa-${new Date().toISOString().slice(0,10)}-${id.slice(0,8)}`;const {rows}=await pool.query(`INSERT INTO accessibility_reports(audit_id,slug,snapshot,published_by) VALUES($1,$2,$3,$4) RETURNING id,slug,published_at,is_current`,[id,slug,JSON.stringify(snapshot),u.sub]);return rows[0]});
 app.get('/api/admin/accessibility/reports',async(req,reply)=>{if(!await admin(req,reply))return;const {rows}=await pool.query(`SELECT r.id,r.slug,r.published_at,r.unpublished_at,r.is_current,a.title,a.application_version FROM accessibility_reports r JOIN accessibility_audits a ON a.id=r.audit_id ORDER BY r.published_at DESC`);return rows});
 app.post('/api/admin/accessibility/reports/:id/unpublish',async(req,reply)=>{if(!await admin(req,reply))return;await pool.query(`UPDATE accessibility_reports SET is_current=false,unpublished_at=now() WHERE id=$1`,[(req.params as any).id]);return{ok:true}});
 app.get('/api/accessibility/report/current',async()=>{const {rows}=await pool.query(`SELECT slug,published_at,snapshot FROM accessibility_reports WHERE is_current=true AND unpublished_at IS NULL ORDER BY published_at DESC LIMIT 1`);return rows[0]||null});
 app.get('/accessibilite/rapports/:slug',async(req,reply)=>{const {rows}=await pool.query(`SELECT slug,published_at,snapshot FROM accessibility_reports WHERE slug=$1 AND unpublished_at IS NULL`,[(req.params as any).slug]);if(!rows.length)return reply.code(404).type('text/html; charset=utf-8').send('<h1>Rapport introuvable</h1>');const html=publicReportHtml(rows[0]);if(!html)return reply.code(500).type('text/html; charset=utf-8').send('<h1>Rapport illisible</h1>');return reply.type('text/html; charset=utf-8').header('Cache-Control','public, max-age=300').send(html)});
 app.get('/api/accessibility/reports/:slug',async(req,reply)=>{const {rows}=await pool.query(`SELECT slug,published_at,snapshot FROM accessibility_reports WHERE slug=$1 AND unpublished_at IS NULL`,[(req.params as any).slug]);if(!rows.length)return reply.code(404).send({error:'NOT_FOUND'});return rows[0]});
}
